database:
  storage: 5Gi
  storageClassName: "local-path"

llm:
  enabled: true
  model: "llama3.1:8b"
  storage: 20Gi
  storageClassName: "local-path"
  provider: "ollama"
  url: "http://llm:11434"

mongo:
  url: "mongodb://mongo:27017"

image:
  pullPolicy: IfNotPresent

query: "Durchsuche das Internet nach den Versprechen von Friedrich Merz."
