database:
  storage: 5Gi

llm:
  enabled: true
  model: "llama3.1:8b"
  storage: 20Gi

image:
  pullPolicy: IfNotPresent
env:
  LLM_PROVIDER: "ollama"
  MODEL: "llama3.1:8b"
  LLM_URL: "http://llm:11434"
  MONGO_URL: "mongodb://mongo:27017"
  QUERY: "Search the internet for the promises of Friedrich Merz."
