database:
  storage: 50Gi

llm:
  enabled: true
  model: "qwen3:8b"
  storage: 100Gi

image:
  pullPolicy: Always
env:
  LLM_PROVIDER: "ollama"
  MODEL: "qwen3:8b"
  LLM_URL: "http://llm:11434"
  MONGO_URL: "mongodb://mongo:27017"
  QUERY: "Search the internet for the promises of Friedrich Merz."
