database:
  storage: 50Gi

llm:
  enabled: true
  model: "llama3:8b"
  storage: 100Gi
  provider: "ollama"
  url: "http://llm:11434"

mongo:
  url: "mongodb://mongo:27017"

image:
  pullPolicy: Always

query: "Durchsuche das Internet nach den Versprechen von Friedrich Merz."
