apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location / {
          proxy_pass http://{{ .Values.upstreams.frontend }};
        }

        location /api/ {
          proxy_pass http://{{ .Values.upstreams.backend }}/;
        }

        location /auth/ {
          proxy_pass http://{{ .Values.upstreams.keycloak }}/;
        }
      }
    }
