{{- if eq .Values.database.storageClassName "" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: {{ .Values.database.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo
  claimRef:
    namespace: agent
    name: mongo-data
{{- end }}
