apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.database.storageClassName }}
  storageClassName: {{ .Values.database.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.storage }}
