apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.database.storage }}
