environments:
  local:
    values:
      - environments/local.yaml
  prod:
    values:
      - environments/prod.yaml

---

releases:
  - name: database
    chart: ./charts/database
    namespace: agent
    values:
      - charts/database/values.yaml
      - environments/{{ .Environment.Name }}.yaml

  - name: llm
    chart: ./charts/llm
    namespace: agent
    values:
      - charts/llm/values.yaml
      - environments/{{ .Environment.Name }}.yaml

  - name: secrets
    chart: ./charts/secrets
    namespace: agent

  - name: agent
    chart: ./charts/agent
    namespace: agent
    needs:
      - agent/llm
      - agent/database
      - agent/secrets
    values:
      - charts/agent/values.yaml
      - environments/{{ .Environment.Name }}.yaml
