agent:
  image:
    repository: agent
    tag: latest
    pullPolicy: Never
  env:
    LLM_URL: "http://llm:11434"
    MONGO_URL: "mongodb://mongo:27017"
    QUERY: ""

llm:
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  env:
    MODEL: "llama3.2"
  storage: 20Gi

mongo:
  image:
    repository: mongo
    tag: "8"
    pullPolicy: IfNotPresent
  storage: 5Gi
