apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.llm.storageClassName }}
  storageClassName: {{ .Values.llm.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.llm.storage }}
